solved exercise 7-5-8
rmohashi/gcc-arm pull request #12
Opened 2018-07-04 01:25 UTC by BrunoSaito

2018-07-04 01:55 UTC, rmohashi commented on src/10/7-5-5.s
> +	STR	r1, [r0]	/* seta os segmentos do display como output e os DIP switches como inputs */
@BrunoSaito Não era pra dar `clear` no bits [3:0]? Acho que o que vc fez aqui é o do display de 7 segmentos.

2018-07-04 01:59 UTC, rmohashi commented on src/10/7-5-5.s
> +	STR	r1, [r0]	/* seta os segmentos do display como output e os DIP switches como inputs */
E se vc queria usar os LEDs, não é desse jeito. Olha o que eu fiz que é o que vc tem que fazer pra usar leds

2018-07-04 02:01 UTC, BrunoSaito commented on src/10/7-5-5.s
> +	STR	r1, [r0]	/* seta os segmentos do display como output e os DIP switches como inputs */
Mas desse jeito já não tá dando clear nos bits [3:0]? 
E tô usando só o display de 7 segmentos e os DIP switches.

2018-07-04 02:04 UTC, BrunoSaito commented on src/10/7-5-5.s
> +	STR	r1, [r0]	/* seta os segmentos do display como output e os DIP switches como inputs */
ah era pra usar os LEDs mesmo no 7-5-5, fiz o exerício 7-5-8, na verdade então.

2018-07-04 02:05 UTC, rmohashi requested changes

2018-07-04 02:05 UTC, rmohashi commented on src/10/7-5-5.s
> +	LDR	r1, [r0]	/* r1 = conteudo de IOPDATA */
@BrunoSaito Não entendi o que vc fez...Era só pra vc pegar os 4 bits menos significativo que tavam nesse r1 e passar pros leds...

2018-07-04 02:08 UTC, BrunoSaito commented on src/10/7-5-5.s
> +	LDR	r1, [r0]	/* r1 = conteudo de IOPDATA */
pois é, eu fiz o 7-5-8 pensando que era o 7-5-5. O 7-5-5 é bem mais tranquilo.

2018-07-04 02:18 UTC, rmohashi requested changes

2018-07-04 02:18 UTC, rmohashi commented on src/10/7-5-5.s
> +	LDR	r1, [r0]	/* r1 = conteudo de IOPDATA */
mesmo assim, eu acho que se vc usasse a estratégia que o @DanZambuja usou(colocando tudo num vetor de `.word` e dando um load com um offset) ia ficar mais claro

2018-07-12 18:16 UTC, rmohashi commented
@BrunoSaito  vou dar close nisso, já que não é mais necessário

2018-07-12 18:16 UTC, closed without merging